server:
  port: 8080
  servlet:
    context-path: /system

spring:
  application:
    name: system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/opentelemetry
    username: root
    password: root

    sql:
      init:
        mode: always

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        data-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
